language: c
sudo: false
env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - LISP=sbcl-bin

os:
  - windows
  - osx
  - linux

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros asdf install
  - if ! [ -f "$HOME/lisp/sn.github/sn.github.asd" ]; then git clone https://github.com/snmsts/sn.github.git ~/lisp/sn.github;fi
  - ros ./scripts/release.ros dummy

cache:
  directories:
    - $HOME/.roswell
    - $HOME/lisp

before_script:
  - ros version
  - ros config
  - ros build proxy.ros
  - echo 'proxy = "http://localhost:5000"' > ~/.curlrc
  - ./proxy daemon
  - sleep 3

script:
  - curl http://www.google.com
  - rm ~/.curlrc
  - cat /tmp/proxy-log

after_success:
  - if [ x$TRAVIS_TAG != x ]; then tar czvf $TRAVIS_TAG-$TRAVIS_OS_NAME.tgz proxy;fi
  - if [ x$TRAVIS_TAG != x ]; then ros ./scripts/release.ros github $TRAVIS_TAG-$TRAVIS_OS_NAME.tgz $TRAVIS_TAG snmsts roswell-proxy;fi
