language: c
sudo: false
env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - LISP=ccl-bin

os:
  - osx
  - linux

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh

cache:
  directories:
    - $HOME/.roswell

before_script:
  - ros version
  - ros config

script:
  - ros build proxy.ros
  - echo 'proxy = "http://localhost:5000"' > ~/.curlrc
  - ./proxy &
  - curl http://www.google.com
